# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SP_PODS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SP_PODS

pod 'Alamofire', '~> 5.5'

  target 'SP_PODSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SP_PODSUITests' do
    # Pods for testing
  end

end
